[package]
name = "simple-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "3.0.34"
axum = "0.4.8"
tokio = {version="1.17.0",features=["full"]}
